In [31]:
import pandas as pd
import numpy as np
import plotly.express as px
from scipy.constants import Planck, elementary_charge, speed_of_light

In [ ]:
def calcular_energia_foton(longitud_nm):
    return (Planck * speed_of_light / (longitud_nm * 1e-9)) / elementary_charge

In [48]:
df = pd.read_csv("data_2023.csv")
df["U_media"] = df[["G1", "G2", "G3"]].mean(axis=1).round(3)
df.sort_values("U_media", ascending=False, inplace=True)
df["E_foton[eV]"] = calcular_energia_foton(df["long [nm]"]).round(3)
df["Ua"] = df["E_foton[eV]"]  - df["U_media"]

Ua_media = df["Ua"].mean()
df

      color  long [nm]    G1   G2    G3  U_media  E_foton[eV]     Ua
1   violeta      436.0  1.20  1.3  1.30    1.267        2.844  1.577
2     verde      546.0  0.75  0.8  0.77    0.773        2.271  1.498
0  amarillo      578.0  0.70  0.5  0.65    0.617        2.145  1.528

In [68]:
df_colores = pd.read_csv("colores.csv")
df_colores["E_max_foton[eV]"] = df_colores["L_min[nm]"].apply(calcular_energia_foton).round(3)
df_colores["E_min_foton[eV]"] = df_colores["L_max[nm]"].apply(calcular_energia_foton).round(3)
df_colores["Uo"] = df_colores["E_min_foton[eV]"] - Ua_media
df_pwm = df_colores[["Color", "Uo"]].sort_values("Uo", ascending=False).copy()
df_colores

      Color  L_min[nm]  L_max[nm]  E_max_foton[eV]  E_min_foton[eV]        Uo
0      Rojo        620        750            2.000            1.653  0.118667
1   Naranja        590        620            2.101            2.000  0.465667
2  Amarillo        570        590            2.175            2.101  0.566667
3     Verde        495        570            2.505            2.175  0.640667
4      Azul        427        495            2.904            2.505  0.970667
5   Violeta        380        427            3.263            2.904  1.369667

In [ ]:
df_pwm["Ganancia"] = df_pwm["Uo"] / 3.3
df_pwm["Division"] = (df_pwm["Ganancia"].max() / df_pwm["Ganancia"]).round(2)
df_pwm

      Color        Uo  Ganancia  Division
5   Violeta  1.369667  0.415051      1.00
4      Azul  0.970667  0.294141      1.41
3     Verde  0.640667  0.194141      2.14
2  Amarillo  0.566667  0.171717      2.42
1   Naranja  0.465667  0.141111      2.94
0      Rojo  0.118667  0.035960     11.54